### ISSUE TITLE
Unable to install using pip

### ISSUE THREAD

**Issue by frndadi** [fleetingbytes/rtfparse#1]
I am using extract-msg to parse my .msg file in one of my project.  Now I need to convert my msg file into html in order to display it on web.  I explored a bit about rtfparse but when I tried to install it using pip cmd. I got the below error.
![rtf-installation_error](https://user-images.githubusercontent.com/75553319/121517855-71f1f500-ca0d-11eb-9188-d4ef6b369651.PNG)

**Comment by LeandraFichtel** [comment]
You can clone the git repo and can install it from there with `pip install rtfparser/` :D

**Comment by fleetingbytes** [comment]
@LeandraFichtel @frndadi The new rtfparse 0.8.0 should install properly now.
